// frontend/src/app/pages/register/register.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  registerForm: FormGroup;
  isLoading = false;
  errorMessage = '';

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.registerForm = this.fb.group({
      username: ['', [Validators.required, Validators.minLength(3)]],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', [Validators.required]]
    }, { validators: this.passwordMatchValidator });
  }

  passwordMatchValidator(form: FormGroup) {
    const password = form.get('password');
    const confirmPassword = form.get('confirmPassword');

    if (password && confirmPassword && password.value !== confirmPassword.value) {
      confirmPassword.setErrors({ mismatch: true });
      return { mismatch: true };
    }
    return null;
  }

  onSubmit(): void {
    if (this.registerForm.valid) {
      this.isLoading = true;
      this.errorMessage = '';

      const { username, email, password } = this.registerForm.value;

      this.authService.register(email, username, password)
      .then( () => {
        this.isLoading = false;
        this.router.navigate(['/dashboard']);
      })
      .catch((err : any) => {
        this.errorMessage = err.error?.message || 'Đăng ký thất bại';
        this.isLoading = false;
      })
      // .subscribe({
      //   next: () => {
      //     this.router.navigate(['/dashboard']);
      //   },
      //   error: (error : any) => {
      //     this.errorMessage = error.error?.message || 'Đăng ký thất bại';
      //     this.isLoading = false;
      //   },
      //   complete: () => {
      //     this.isLoading = false;
      //   }
      // });
    } else {
      this.markFormGroupTouched();
    }
  }

  private markFormGroupTouched(): void {
    Object.keys(this.registerForm.controls).forEach(key => {
      const control = this.registerForm.get(key);
      control?.markAsTouched();
    });
  }

  getFieldError(fieldName: string): string {
    const control = this.registerForm.get(fieldName);
    if (control?.errors && control.touched) {
      switch (fieldName) {
        case 'username':
          if (control.errors['required']) return 'Vui lòng nhập tên đăng nhập';
          if (control.errors['minlength']) return 'Tên đăng nhập phải có ít nhất 3 ký tự';
          break;
        case 'email':
          if (control.errors['required']) return 'Vui lòng nhập email';
          if (control.errors['email']) return 'Email không hợp lệ';
          break;
        case 'password':
          if (control.errors['required']) return 'Vui lòng nhập mật khẩu';
          if (control.errors['minlength']) return 'Mật khẩu phải có ít nhất 6 ký tự';
          break;
        case 'confirmPassword':
          if (control.errors['required']) return 'Vui lòng xác nhận mật khẩu';
          if (control.errors['mismatch']) return 'Mật khẩu xác nhận không khớp';
          break;
      }
    }
    return '';
  }
}

<div class="container flex min-h-screen max-w-mobile items-center justify-center">
  <div class="w-full space-y-6 px-4">
    <div class="text-center">
      <h1 class="text-2xl font-bold text-gray-900">
        Đăng ký tài khoản
      </h1>
      <p class="mt-2 text-sm text-gray-600">
        Đã có tài khoản?
        <a routerLink="/login" class="font-medium text-blue-600 hover:text-blue-500">
          Đăng nhập ngay
        </a>
      </p>
    </div>

    <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="space-y-4">
      <!-- Username Field -->
      <div class="space-y-2">
        <label class="text-sm font-medium text-gray-700">Tên đăng nhập</label>
        <app-input
          formControlName="username"
          placeholder="Nhập tên đăng nhập"
          [error]="!!getFieldError('username')"
        ></app-input>
        <p *ngIf="getFieldError('username')" class="text-sm text-red-600">
          {{ getFieldError('username') }}
        </p>
      </div>

      <!-- Email Field -->
      <div class="space-y-2">
        <label class="text-sm font-medium text-gray-700">Email</label>
        <app-input
          formControlName="email"
          type="email"
          placeholder="Nhập địa chỉ email"
          [error]="!!getFieldError('email')"
        ></app-input>
        <p *ngIf="getFieldError('email')" class="text-sm text-red-600">
          {{ getFieldError('email') }}
        </p>
      </div>

      <!-- Password Field -->
      <div class="space-y-2">
        <label class="text-sm font-medium text-gray-700">Mật khẩu</label>
        <app-input
          formControlName="password"
          type="password"
          placeholder="Nhập mật khẩu"
          [error]="!!getFieldError('password')"
        ></app-input>
        <p *ngIf="getFieldError('password')" class="text-sm text-red-600">
          {{ getFieldError('password') }}
        </p>
      </div>

      <!-- Confirm Password Field -->
      <div class="space-y-2">
        <label class="text-sm font-medium text-gray-700">Xác nhận mật khẩu</label>
        <app-input
          formControlName="confirmPassword"
          type="password"
          placeholder="Nhập lại mật khẩu"
          [error]="!!getFieldError('confirmPassword')"
        ></app-input>
        <p *ngIf="getFieldError('confirmPassword')" class="text-sm text-red-600">
          {{ getFieldError('confirmPassword') }}
        </p>
      </div>

      <!-- Error Message -->
      <div *ngIf="errorMessage" class="rounded-md bg-red-50 p-4">
        <p class="text-sm text-red-700">{{ errorMessage }}</p>
      </div>

      <!-- Submit Button -->
      <app-button
        type="submit"
        variant="default"
        className="w-full"
        [isLoading]="isLoading"
      >
        Đăng ký
      </app-button>
    </form>

    <!-- Terms and Conditions -->
    <div class="text-center text-xs text-gray-500">
      <p>
        Bằng việc đăng ký, bạn đồng ý với
        <a href="#" class="text-blue-600 hover:text-blue-500">Điều khoản sử dụng</a>
        và
        <a href="#" class="text-blue-600 hover:text-blue-500">Chính sách bảo mật</a>
      </p>
    </div>
  </div>
</div>

// frontend-react-backup/src/pages/Register.tsx
import { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { toast } from 'react-hot-toast'
import { Button } from '@/components/atoms/Button'
import { Input } from '@/components/atoms/Input'
import {
  FormField,
  FormLabel,
  FormMessage,
} from '@/components/molecules/FormField'
import { useAuth } from '@/hooks/useAuth'

const registerSchema = z.object({
  email: z.string().email('Email không hợp lệ'),
  username: z.string().min(1, 'Vui lòng nhập tên đăng nhập'),
  password: z.string()
    .min(6, 'Mật khẩu phải có ít nhất 6 ký tự')
    .max(50, 'Mật khẩu không được quá 50 ký tự'),
  confirmPassword: z.string()
}).refine((data) => data.password === data.confirmPassword, {
  message: "Mật khẩu xác nhận không khớp",
  path: ["confirmPassword"],
})

type RegisterForm = z.infer<typeof registerSchema>

export default function Register() {
  const navigate = useNavigate()
  const { register: registerUser } = useAuth()
  const [isLoading, setIsLoading] = useState(false)

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<RegisterForm>({
    resolver: zodResolver(registerSchema),
  })

  const onSubmit = async (data: RegisterForm) => {
    try {
      setIsLoading(true)
      await registerUser(data.email, data.username, data.password)
      toast.success('Đăng ký thành công')
      navigate('/dashboard')
    } catch (error) {
      console.error('Registration error:', error)
      toast.error('Đăng ký thất bại. Vui lòng thử lại.')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="container flex min-h-screen max-w-mobile items-center justify-center">
      <div className="w-full space-y-6 px-4">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900">
            Đăng ký tài khoản
          </h1>
          <p className="mt-2 text-sm text-gray-600">
            Đã có tài khoản?{' '}
            <Link to="/login" className="font-medium text-primary-600">
              Đăng nhập
            </Link>
          </p>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <FormField>
            <FormLabel>Email</FormLabel>
            <Input
              type="email"
              {...register('email')}
              error={!!errors.email}
            />
            {errors.email && (
              <FormMessage>{errors.email.message}</FormMessage>
            )}
          </FormField>

          <FormField>
            <FormLabel>Tên đăng nhập</FormLabel>
            <Input
              type="text"
              {...register('username')}
              error={!!errors.username}
            />
            {errors.username && (
              <FormMessage>{errors.username.message}</FormMessage>
            )}
          </FormField>

          <FormField>
            <FormLabel>Mật khẩu</FormLabel>
            <Input
              type="password"
              {...register('password')}
              error={!!errors.password}
            />
            {errors.password && (
              <FormMessage>{errors.password.message}</FormMessage>
            )}
          </FormField>

          <FormField>
            <FormLabel>Xác nhận mật khẩu</FormLabel>
            <Input
              type="password"
              {...register('confirmPassword')}
              error={!!errors.confirmPassword}
            />
            {errors.confirmPassword && (
              <FormMessage>{errors.confirmPassword.message}</FormMessage>
            )}
          </FormField>

          <Button type="submit" className="w-full" isLoading={isLoading}>
            Đăng ký
          </Button>
        </form>
      </div>
    </div>
  )
}
