// frontend/src/components/molecules/FormField.tsx
import { HTMLAttributes, forwardRef } from 'react'
import { cn } from '@/utils/cn'

const FormField = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => {
    return (
      <div ref={ref} className={cn('space-y-2', className)} {...props} />
    )
  }
)
FormField.displayName = 'FormField'

const FormLabel = forwardRef<HTMLLabelElement, HTMLAttributes<HTMLLabelElement>>(
  ({ className, ...props }, ref) => {
    return (
      <label
        ref={ref}
        className={cn(
          'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
          className
        )}
        {...props}
      />
    )
  }
)
FormLabel.displayName = 'FormLabel'

const FormDescription = forwardRef<HTMLParagraphElement, HTMLAttributes<HTMLParagraphElement>>(
  ({ className, ...props }, ref) => {
    return (
      <p
        ref={ref}
        className={cn('text-[0.8rem] text-gray-500', className)}
        {...props}
      />
    )
  }
)
FormDescription.displayName = 'FormDescription'

const FormMessage = forwardRef<HTMLParagraphElement, HTMLAttributes<HTMLParagraphElement>>(
  ({ className, children, ...props }, ref) => {
    return (
      <p
        ref={ref}
        className={cn('text-[0.8rem] font-medium text-red-500', className)}
        {...props}
      >
        {children}
      </p>
    )
  }
)
FormMessage.displayName = 'FormMessage'

export { FormField, FormLabel, FormDescription, FormMessage }

// frontend/src/app/components/molecules/form-field.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-form-field',
  template: `
    <div class="space-y-2 {{ className }}">
      <ng-content></ng-content>
    </div>
  `,
  styles: []
})
export class FormFieldComponent {
  @Input() className = '';
}

@Component({
  selector: 'app-form-label',
  template: `
    <label class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 {{ className }}">
      <ng-content></ng-content>
    </label>
  `,
  styles: []
})
export class FormLabelComponent {
  @Input() className = '';
}

@Component({
  selector: 'app-form-description',
  template: `
    <p class="text-[0.8rem] text-gray-500 {{ className }}">
      <ng-content></ng-content>
    </p>
  `,
  styles: []
})
export class FormDescriptionComponent {
  @Input() className = '';
}

@Component({
  selector: 'app-form-message',
  template: `
    <p class="text-[0.8rem] font-medium text-red-500 {{ className }}">
      <ng-content></ng-content>
    </p>
  `,
  styles: []
})
export class FormMessageComponent {
  @Input() className = '';
}
