// frontend-react-backup/src/pages/Login.tsx
import { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { toast } from 'react-hot-toast'
import { Button } from '@/components/atoms/Button'
import { Input } from '@/components/atoms/Input'
import {
  FormField,
  FormLabel,
  FormMessage,
} from '@/components/molecules/FormField'
import { useAuth } from '@/hooks/useAuth'

const loginSchema = z.object({
  username: z.string().min(1, 'Vui lòng nhập tên đăng nhập'),
  password: z.string().min(6, 'Mật khẩu phải có ít nhất 6 ký tự'),
})

type LoginForm = z.infer<typeof loginSchema>

export default function Login() {
  const navigate = useNavigate()
  const { login } = useAuth()
  const [isLoading, setIsLoading] = useState(false)

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<LoginForm>({
    resolver: zodResolver(loginSchema),
  })

  const onSubmit = async (data: LoginForm) => {
    try {
      setIsLoading(true)
      await login(data.username, data.password)
      toast.success('Đăng nhập thành công')
      navigate('/dashboard')
    } catch (error) {
      toast.error('Đăng nhập thất bại')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="container flex min-h-screen max-w-mobile items-center justify-center">
      <div className="w-full space-y-6 px-4">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900">
            Đăng nhập vào Loyalty App
          </h1>
          <p className="mt-2 text-sm text-gray-600">
            Chưa có tài khoản?{' '}
            <Link to="/register" className="font-medium text-primary-600">
              Đăng ký ngay
            </Link>
          </p>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <FormField>
            <FormLabel>Tên đăng nhập</FormLabel>
            <Input
              type="text"
              {...register('username')}
              error={!!errors.username}
            />
            {errors.username && (
              <FormMessage>{errors.username.message}</FormMessage>
            )}
          </FormField>

          <FormField>
            <FormLabel>Mật khẩu</FormLabel>
            <Input
              type="password"
              {...register('password')}
              error={!!errors.password}
            />
            {errors.password && (
              <FormMessage>{errors.password.message}</FormMessage>
            )}
          </FormField>

          <Button type="submit" className="w-full" isLoading={isLoading}>
            Đăng nhập
          </Button>
        </form>
      </div>
    </div>
  )
}

// frontend/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  loginForm: FormGroup;
  isLoading = false;
  errorMessage = '';

  constructor(
    private fb: FormBuilder,
    private apiService: ApiService,
    private authService: AuthService,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      username: ['', [Validators.required]],
      password: ['', [Validators.required, Validators.minLength(6)]]
    });
  }

  async onSubmit(): Promise<void> {
    if (this.loginForm.valid) {
      this.isLoading = true;
      this.errorMessage = '';

      const { username, password } = this.loginForm.value;

      try {
        await this.authService.login(username, password);
        this.isLoading = false;
        this.router.navigate(['/dashboard']);
      } catch (error: any) {
        this.errorMessage = error.error?.message || 'Đăng nhập thất bại';
        this.isLoading = false;
      }
    } else {
      this.markFormGroupTouched();
    }
  }

  private markFormGroupTouched(): void {
    Object.keys(this.loginForm.controls).forEach(key => {
      const control = this.loginForm.get(key);
      control?.markAsTouched();
    });
  }

  getFieldError(fieldName: string): string {
    const control = this.loginForm.get(fieldName);
    if (control?.errors && control.touched) {
      if (control.errors['required']) {
        return fieldName === 'username' ? 'Vui lòng nhập tên đăng nhập' : 'Vui lòng nhập mật khẩu';
      }
      if (control.errors['minlength']) {
        return 'Mật khẩu phải có ít nhất 6 ký tự';
      }
    }
    return '';
  }
}

<div class="container flex min-h-screen max-w-mobile items-center justify-center">
  <div class="w-full space-y-6 px-4">
    <div class="text-center">
      <h1 class="text-2xl font-bold text-gray-900">
        Đăng nhập vào Loyalty App
      </h1>
      <p class="mt-2 text-sm text-gray-600">
        Chưa có tài khoản?
        <a routerLink="/register" class="font-medium text-blue-600 hover:text-blue-500">
          Đăng ký ngay
        </a>
      </p>
    </div>

    <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="space-y-4">
      <!-- Username Field -->
      <div class="space-y-2">
        <label class="text-sm font-medium text-gray-700">Tên đăng nhập</label>
        <app-input
          formControlName="username"
          placeholder="Nhập tên đăng nhập"
          [error]="!!getFieldError('username')"
        ></app-input>
        <p *ngIf="getFieldError('username')" class="text-sm text-red-600">
          {{ getFieldError('username') }}
        </p>
      </div>

      <!-- Password Field -->
      <div class="space-y-2">
        <label class="text-sm font-medium text-gray-700">Mật khẩu</label>
        <app-input
          formControlName="password"
          type="password"
          placeholder="Nhập mật khẩu"
          [error]="!!getFieldError('password')"
        ></app-input>
        <p *ngIf="getFieldError('password')" class="text-sm text-red-600">
          {{ getFieldError('password') }}
        </p>
      </div>

      <!-- Error Message -->
      <div *ngIf="errorMessage" class="rounded-md bg-red-50 p-4">
        <p class="text-sm text-red-700">{{ errorMessage }}</p>
      </div>

      <!-- Submit Button -->
      <app-button
        type="submit"
        variant="default"
        className="w-full"
        [isLoading]="isLoading"
      >
        Đăng nhập
      </app-button>
    </form>
  </div>
</div>
