// frontend/src/app/pages/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { map } from 'rxjs/operators';
import { PointsService } from '../../services/points.service';

interface Voucher {
  id: string;
  title: string;
  description: string;
  points: number;
  expiryDate: string;
}

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent {
  points$ = this.pointsService.pointsData$.pipe(
    map(data => data.balance)
  );

  transactions$ = this.pointsService.pointsData$.pipe(
    map(data => data.transactions.slice(0, 5))
  );

  isLoading$ = this.pointsService.isLoading$;

  vouchers: Voucher[] = [
    {
      id: '1',
      title: 'Giảm 50k',
      description: 'Áp dụng cho đơn hàng từ 500k',
      points: 1000,
      expiryDate: '2024-12-31',
    },
    {
      id: '2',
      title: 'Freeship',
      description: 'Miễn phí vận chuyển toàn quốc',
      points: 500,
      expiryDate: '2024-12-31',
    },
  ];

  constructor(
    private router: Router,
    private pointsService: PointsService
  ) {}

  onEarn(): void {
    this.router.navigate(['/earn']);
  }

  onTransfer(): void {
    this.router.navigate(['/transfer']);
  }

  onRedeem(voucherId: string): void {
    this.router.navigate(['/voucher', voucherId]);
  }
}

<div class="container max-w-mobile space-y-6 p-4">
  <div class="space-y-2">
    <h1 class="text-2xl font-bold">Xin chào!</h1>
    <p class="text-gray-500">
      Chào mừng bạn đến với chương trình Loyalty Points
    </p>
  </div>

  <!-- Points Card -->
  <app-points-card
    [points]="points$ | async"
    (onEarn)="onEarn()"
    (onTransfer)="onTransfer()"
  ></app-points-card>

  <!-- Stats Cards -->
  <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
    <app-card>
      <app-card-header className="flex flex-row items-center space-x-4 pb-2">
        <div class="flex h-12 w-12 items-center justify-center rounded-lg bg-blue-100">
          <svg class="h-6 w-6 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"/>
          </svg>
        </div>
        <div>
          <app-card-title className="text-base font-semibold">Quà tặng</app-card-title>
          <p class="text-sm text-gray-500">Đổi điểm lấy quà</p>
        </div>
      </app-card-header>
      <app-card-content>
        <div class="text-2xl font-bold text-blue-600">5</div>
        <p class="text-sm text-gray-500">Quà tặng khả dụng</p>
      </app-card-content>
    </app-card>

    <app-card>
      <app-card-header className="flex flex-row items-center space-x-4 pb-2">
        <div class="flex h-12 w-12 items-center justify-center rounded-lg bg-blue-100">
          <svg class="h-6 w-6 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 5v2m0 4v2m0 4v2M5 5a2 2 0 00-2 2v8a2 2 0 002 2h14a2 2 0 002-2V7a2 2 0 00-2-2h-3"/>
          </svg>
        </div>
        <div>
          <app-card-title className="text-base font-semibold">Voucher</app-card-title>
          <p class="text-sm text-gray-500">Ưu đãi của bạn</p>
        </div>
      </app-card-header>
      <app-card-content>
        <div class="text-2xl font-bold text-blue-600">3</div>
        <p class="text-sm text-gray-500">Voucher chưa sử dụng</p>
      </app-card-content>
    </app-card>
  </div>

  <!-- Voucher Grid -->
  <div class="space-y-4">
    <h2 class="text-lg font-semibold">Voucher nổi bật</h2>
    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
      <app-card *ngFor="let voucher of vouchers" class="cursor-pointer" (click)="onRedeem(voucher.id)">
        <app-card-header>
          <app-card-title>{{ voucher.title }}</app-card-title>
          <app-card-description>{{ voucher.description }}</app-card-description>
        </app-card-header>
        <app-card-content>
          <div class="flex items-center justify-between">
            <span class="text-sm text-gray-500">{{ voucher.points }} điểm</span>
            <span class="text-sm text-gray-500">{{ voucher.expiryDate }}</span>
          </div>
        </app-card-content>
      </app-card>
    </div>
  </div>

  <!-- Recent Transactions -->
  <div class="space-y-4">
    <div class="flex items-center justify-between">
      <h2 class="text-lg font-semibold">Giao dịch gần đây</h2>
      <a routerLink="/transactions" class="text-blue-600 hover:text-blue-500 text-sm font-medium">
        Xem tất cả →
      </a>
    </div>
    <div class="space-y-2">
      <div *ngFor="let transaction of transactions$ | async" class="flex items-center justify-between p-3 border rounded-lg">
        <div>
          <p class="font-medium">{{ transaction.description }}</p>
          <p class="text-sm text-gray-500">{{ transaction.timestamp | date:'short' }}</p>
        </div>
        <div class="text-right">
          <p class="font-semibold" [ngClass]="{
            'text-green-600': transaction.type === 'EARN',
            'text-red-600': transaction.type === 'REDEEM',
            'text-blue-600': transaction.type === 'TRANSFER'
          }">
            {{ transaction.type === 'EARN' ? '+' : transaction.type === 'REDEEM' ? '-' : '' }}{{ transaction.amount }}
          </p>
          <app-badge [variant]="transaction.status === 'success' ? 'success' : 'destructive'">
            {{ transaction.status }}
          </app-badge>
        </div>
      </div>
    </div>
  </div>

  <!-- Loading State -->
  <div *ngIf="isLoading$ | async" class="flex justify-center py-8">
    <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
  </div>
</div>

// frontend/src/pages/Dashboard.tsx
import { useNavigate } from 'react-router-dom'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/atoms/Card'
import { PointsCard } from '@/components/molecules/PointsCard'
import { TransactionList } from '@/components/organisms/TransactionList'
import { VoucherGrid } from '@/components/organisms/VoucherGrid'
import { usePoints } from '@/hooks/usePoints'
import { Gift, Ticket } from 'lucide-react'

export default function Dashboard() {
  const navigate = useNavigate()
  const { points, transactions, isLoading } = usePoints()

  // Mock data for vouchers
  const vouchers = [
    {
      id: '1',
      title: 'Giảm 50k',
      description: 'Áp dụng cho đơn hàng từ 500k',
      points: 1000,
      expiryDate: '2024-12-31',
    },
    {
      id: '2',
      title: 'Freeship',
      description: 'Miễn phí vận chuyển toàn quốc',
      points: 500,
      expiryDate: '2024-12-31',
    },
  ]

  return (
    <div className="container max-w-mobile space-y-6 p-4">
      <div className="space-y-2">
        <h1 className="text-2xl font-bold">Xin chào!</h1>
        <p className="text-gray-500">
          Chào mừng bạn đến với chương trình Loyalty Points
        </p>
      </div>

      <PointsCard
        points={points}
        onEarn={() => navigate('/earn')}
        onTransfer={() => navigate('/transfer')}
      />

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <Card>
          <CardHeader className="flex flex-row items-center space-x-4 pb-2">
            <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary-100">
              <Gift className="h-6 w-6 text-primary-600" />
            </div>
            <div>
              <CardTitle className="text-base font-semibold">Quà tặng</CardTitle>
              <p className="text-sm text-gray-500">Đổi điểm lấy quà</p>
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-primary-600">5</div>
            <p className="text-sm text-gray-500">Quà tặng khả dụng</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center space-x-4 pb-2">
            <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary-100">
              <Ticket className="h-6 w-6 text-primary-600" />
            </div>
            <div>
              <CardTitle className="text-base font-semibold">Voucher</CardTitle>
              <p className="text-sm text-gray-500">Ưu đãi của bạn</p>
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-primary-600">3</div>
            <p className="text-sm text-gray-500">Voucher chưa sử dụng</p>
          </CardContent>
        </Card>
      </div>

      <div className="space-y-4">
        <h2 className="text-lg font-semibold">Voucher nổi bật</h2>
        <VoucherGrid
          vouchers={vouchers}
          onRedeem={(id) => navigate(`/voucher/${id}`)}
        />
      </div>

      <div className="space-y-4">
        <h2 className="text-lg font-semibold">Giao dịch gần đây</h2>
        <TransactionList
          transactions={transactions.slice(0, 5)}
          isLoading={isLoading}
        />
      </div>
    </div>
  )
}
